### PR TITLE
feat: support empty values

### LINKED ISSUE #9: Support null/empty values
This is a feature request.

When I add empty env variables like:

```
ELASTICSEARCH_TEST_URL=
```

Or:

```
ELASTICSEARCH_TEST_URL=""
```

These are not resolved, and therefore not available in the program code.

Feature: Make empty variables available in `Env`, but simply set to an empty string (in case of `""`), or `null` (in case of no value) so that you can programmatically deal with them and determine absence of the values.

Otherwise I have no easy way to provide optional values.

Consider the case where this `.env` file is necessary for a certain functionality only, so the values don't have to be set at all times. I cannot just remove them completely, as the code wouldn't compile anymore. I also cannot set them to bogus values like `foo`, because I would have to provide extra check like `if Env.elasticsearchTestUrl == "foo"` instead of a semantically more correct `if Env.elasticsearchTestUrl == null`, or add a check for `.length() == 0`.

### PR DESCRIPTION
**Pull request by slhck**

### CODE REVIEW

**Comment by levibostian** [comment]
Looks great! I would, however, like to include a test to test this works. 

You can try doing this yourself by modifying the files in [this directory](https://github.com/levibostian/dotenv/tree/main/e2e/kotlin_to_java). You should only need to modify the `.env`, `Given.kt`, and `Expected.java` files.

**Comment by slhck** [comment]
I added the test but it seems it's failing. I am getting other errors though; I've never worked with Go before, so I don't know off the top of my head what's wrong.

```
✓  lang (cached)
✓  e2e/multiple_input_lang (cached)
✓  util (cached)
∅  .
∅  cmd
∅  config
✖  e2e (98ms)
∅  e2e/helpers
✖  e2e/kotlin_to_java (175ms)
∅  generate
∅  types
∅  ui

=== Failed
=== FAIL: e2e Test_Version_expectValidValue (0.00s)
2021/08/23 20:52:59 fork/exec ../dotenv: no such file or directory
version_test.go:14  should not be equal 

=== FAIL: e2e/kotlin_to_java Test_GenerateJavaFromKotlinSource_expectFileGenerated (0.00s)
2021/08/23 20:52:59 fork/exec ../../dotenv: no such file or directory
generate_test.go:19 package earth.levi.dotenv;

/**
 * This file is automatically generated. Do not modify. 
 */
public final class Env {
    public static String barBar = "hello";
    public static String fooFoo = "world";
    public static String bazBaz = "";
}
 does not equal package earth.levi.dotenv;

/**
 * This file is automatically generated. Do not modify. 
 */
public final class Env {
    public static String barBar = "hello";
    public static String fooFoo = "world";
}


DONE 35 tests, 2 failures in 0.546s
```

**Comment by levibostian** [comment]
You're doing outstanding, @slhck. Even without Go experience, you have been doing great. I appreciate your efforts. 

The `dotenv` CLI generates the exported code in alphabetical order. I just had to change the order of the properties and the tests now pass. 

Shipping! 

@all-contributors add @slhck for code

**Comment by slhck** [comment]
Ah, I was simply too tired to see this. Thank you for merging it so quickly!

**Comment by levibostian** [comment]
I know that you did this work to ultimately support this feature in the android plugin. I [merged in the PR](https://github.com/levibostian/dotenv-android/pull/25) to get that updated and [it's deploying now](https://github.com/levibostian/dotenv-android/actions/runs/1160104519).

**Comment by levibostian** [comment]
[Deployed](https://github.com/levibostian/dotenv-android/releases/tag/1.3.0) 🎊

**Pull request merged**
